FROM ryanckoch/docker-nginx-ssl-secure
MAINTAINER Ryan C Koch "ryanckoch@gmail.com"

ADD external /etc/nginx/external
ADD docker-registry.conf /etc/nginx/conf.d/docker-registry.conf
ADD docker-registry-frontend.conf /etc/nginx/conf.d/docker-registry-frontend.conf
